version: '3.3'
services:
  
  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5435:5435
    networks:
      - heart

  backend:
    container_name: backend
    build: ./backend/
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - heart

  bot:
    container_name: bot
    build: ./bot/
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - heart

  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
    restart: always
    networks:
      - heart

volumes:
  db_value:
  static_value:
  media_value:

networks:
  heart:
    driver: bridge
